# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('random_item', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='word_text',
            new_name='text',
        ),
    ]
