# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_item', '0002_auto_20160119_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=256)),
                ('translation', models.CharField(max_length=1024)),
            ],
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
